services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: bank-simulation
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/bank-simulator
    depends_on:
      - mongo

volumes:
  mongo-data:
